[platformio]
default_envs = waveshare-touch-28

[env:waveshare-touch-28]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_qspi
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    lovyan03/LovyanGFX@^1.2.27
    lewisxhe/SensorLib@^0.4.1
    mikalhart/TinyGPSPlus@^1.0.3

[env:tbeam-supreme]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
lib_deps =
    mikalhart/TinyGPSPlus@^1.0.3
    olikraus/U8g2@^2.35.9
    lewisxhe/XPowersLib@^0.2.3
